# -*- coding: utf-8 -*-
"""Stopwords.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fuKv-3I4A9lo_hAdvLkEjLqNwjIpRxp7
"""

# enlever les mots les plus courants en anglais
STOPWORDS = set(['the', 'is', 'an', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have',
                 'I', 'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you',
                 'do', 'at', 'this', 'but', 'his', 'by', 'from'])

text = data['Title'][0]

tokens = text.lower()
tokens = tokens.split()
filtered_text = []

for w in tokens:
  if w not in STOPWORDS:
    filtered_text.append(w)

print(filtered_text)